server:
  port: 8080
  address: 0.0.0.0
  forward-headers-strategy: framework


spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        auto_quote_keyword: true
        globally_quoted_identifiers: true
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT}
            scope: profile, email

openai:
  secret: ${AI_KEY}
  url: ${AI_URL}

logging:
  level:
    root: INFO

springdoc:
  override-with-generic-response: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
    path: "swagger.html"

jwt:
  secret: RjmvkEUizZYUTz6JHVE4LtYPL0k8eMF0